// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3853.NewRobot10122015.subsystems;

import org.usfirst.frc3853.NewRobot10122015.RobotMap;
import org.usfirst.frc3853.NewRobot10122015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Elevator extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput limitSwitchTop = RobotMap.elevatorLimitSwitchTop;
    DigitalInput limitSwitchBottom = RobotMap.elevatorLimitSwitchBottom;
    SpeedController liftMotor = RobotMap.elevatorLiftMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
public void limitSwitchTop() {
    	
    	liftMotor.set(.5);
    }
    public void limitSwitchBottom() {
    	liftMotor.set(-.5);
    }
    public void stop() {
    	liftMotor.set(0.0);
    }
}

